# Generated by Django 4.2 on 2026-04-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('bank_account', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_percentage', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('genuine', 'Genuine'), ('suspicious', 'Suspicious'), ('fake', 'Fake'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('identity', 'Identity Proof'), ('income', 'Income Certificate'), ('academic', 'Academic Certificate'), ('bank', 'Bank Passbook')], max_length=50)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('tamper_score', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
    ]
