# Generated by Django 4.2 on 2026-04-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('duplicate_phone', 'Duplicate Phone'), ('duplicate_email', 'Duplicate Email'), ('duplicate_aadhaar', 'Duplicate Aadhaar'), ('duplicate_bank', 'Duplicate Bank Account'), ('bulk_submission', 'Bulk Submission'), ('ip_reuse', 'IP Address Reuse'), ('doc_tamper', 'Document Tampering'), ('ml_anomaly', 'ML Anomaly Detected')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='applications.application')),
            ],
        ),
    ]
